### ISSUE TITLE
Unable to run boot_docker

### ISSUE THREAD

**Issue by huang-ying** [broadinstitute/single_cell_portal_core#36]
Can't finish boo_docker due to "rake aborted", as shown below. Google search indicates a RVM environment problem. My environment is MacBook Pro with OS X El Capitan 10.11.6 + 16GB RAM + Docker CE Version 17.06.1-ce-mac24 (18950)

bin/boot_docker -e test
Seeding test database...
rake aborted!
Errno::EISDIR: Is a directory @ io_fread - /home/app/webapp
/usr/local/rvm/gems/ruby-2.3.1/gems/googleauth-0.5.1/lib/googleauth/service_account.rb:75:in `read'
/usr/local/rvm/gems/ruby-2.3.1/gems/googleauth-0.5.1/lib/googleauth/service_account.rb:75:in `read_json_key'
/usr/local/rvm/gems/ruby-2.3.1/gems/googleauth-0.5.1/lib/googleauth/service_account.rb:59:in `make_creds'
/home/app/webapp/app/models/fire_cloud_client.rb:72:in `generate_access_token'
/home/app/webapp/app/models/fire_cloud_client.rb:32:in `initialize'
/home/app/webapp/app/models/study.rb:9:in `new'
/home/app/webapp/app/models/study.rb:9:in `<class:Study>'
/home/app/webapp/app/models/study.rb:1:in `<top (required)>'

**Comment by bistline** [comment]
If you're looking just to use the portal, please visit [https://portals.broadinstitute.org/single_cell](https://portals.broadinstitute.org/single_cell) and log in to create an account and begin browsing public studies or create your own.  It is not necessary to run your own instance of the portal.  More information on how to use the portal can be found here: [https://github.com/broadinstitute/single_cell_portal/wiki](https://github.com/broadinstitute/single_cell_portal/wiki)

However, if you are trying to start your own private instance (even just running the unit tests), the Single Cell Portal is configured to use a service account that corresponds to the Google Compute Project that it is deployed in.  The error message you're seeing is because you do not have the JSON credentials loaded into the application environment (passed with -k in bin/boot_docker).  In order to get your own instance running, you will need to do the following:

1. Create a Google Cloud Platform project
2. Export the default service account credentials for that project to a JSON file

You will then be able to run the portal in test mode like you were trying earlier.  If you want to stand up an instance elsewhere to actually use, there are 3 additional steps:

1. Create a [FireCloud](https://software.broadinstitute.org/firecloud) Billing project (more info found [here](https://software.broadinstitute.org/firecloud/documentation/article?id=9763))
2. Add your service account email as a project owner of the FireCloud project you just created
3. Inside the portal codebase, edit app/models/fire_cloud_client.rb (line 17)

PORTAL_NAMESPACE = 'name of your FireCloud project' 

You will then be able to run the portal using the service account credentials you exported earlier.  You can run the portal locally via Docker, or deploy it inside a GCP VM and run it remotely.  But it requires service account credentials either way.
